version: '3.8'

services:
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - rag-network

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - VECTOR_DB_PROVIDER=chroma
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    env_file:
      - .env
    depends_on:
      - chroma
    networks:
      - rag-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_MCP_PROXY=/api/mcp-proxy
    env_file:
      - .env
    depends_on:
      - mcp-server
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  chroma_data:

networks:
  rag-network:
    driver: bridge
